In [3]:
# importing libraries and dataset
import pandas as pd
df = pd.read_csv("Dataset.csv")
df["Cuisines"]=df["Cuisines"].fillna("Unknown")
rows,columns = df.shape
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [6]:
# there are some coloumn values which has some invalid characters "?"
accented_columns = ['Restaurant Name','City','Address','Locality','Locality Verbose','Cuisines']
from unidecode import unidecode
def clean_text(text):
    if isinstance(text,str):
        return unidecode(text)
    return text
df[accented_columns]=df[accented_columns].applymap(clean_text)
df.tail()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9546,5915730,Naml1 Gurme,208,stanbul,"Kemanke Karamustafa Paa Mahallesi, R1ht1m Cadd...",Karak_y,"Karak_y, stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz Aac1,208,stanbul,"Kouyolu Mahallesi, Muhittin st_nda Caddesi, No...",Kouyolu,"Kouyolu, stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,stanbul,"Kuru_eme Mahallesi, Muallim Naci Caddesi, No 5...",Kuru_eme,"Kuru_eme, stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Ak Kahve,208,stanbul,"Kuru_eme Mahallesi, Muallim Naci Caddesi, No 6...",Kuru_eme,"Kuru_eme, stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,stanbul,"Cafeaa Mahallesi, Bademalt1 Sokak, No 21/B, Ka...",Moda,"Moda, stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [9]:
# exporting the cleaned dataset
SD = df.to_csv("cleaned1.csv",index=False)

# Resturant Recommendation with Cuisines

In [20]:
import pandas as pd

# Read the CSV file into a DataFrame
df1 = pd.read_csv("cleaned1.csv")
rows,columns = df1.shape

# Display the DataFrame
df1.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [21]:
df1.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [23]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Read the CSV file into a DataFrame
df1 = pd.read_csv("cleaned1.csv")

# Extracting features
y = df1['Restaurant Name']
x_text = df1['Cuisines'] + " " + df1['Rating color'] + " " + df1['Rating text'] + " " + df1["Votes"].astype(str) + " " + df1["Price range"].astype(str)

# Create a TF-IDF vectorizer
tfidf = TfidfVectorizer()

# Transform the text data using TF-IDF
x = tfidf.fit_transform(x_text)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
similarityScore = cosine_similarity(x)
similarityScore

array([[1.        , 0.42113843, 0.04186458, ..., 0.        , 0.04188754,
        0.05554734],
       [0.42113843, 1.        , 0.04931748, ..., 0.        , 0.04934452,
        0.65120488],
       [0.04186458, 0.04931748, 1.        , ..., 0.01981244, 0.11616055,
        0.15404129],
       ...,
       [0.        , 0.        , 0.01981244, ..., 1.        , 0.01982331,
        0.02628782],
       [0.04188754, 0.04934452, 0.11616055, ..., 0.01982331, 1.        ,
        0.24058858],
       [0.05554734, 0.65120488, 0.15404129, ..., 0.02628782, 0.24058858,
        1.        ]])

In [26]:
userInput = input("Enter Your Preferred Cuisines :")
cuisineList = df1["Cuisines"]
for i in range(len(cuisineList)):
    if userInput in cuisineList[i]:
        k = df1.iloc[i]['Restaurant Name']
        index = i
        break
RecommendationScore = list(enumerate(similarityScore[index]))

Enter Your Preferred Cuisines :Japanese

In [29]:
# Recommendation of Resturant
sortedResturantList = sorted(RecommendationScore,key=lambda x:x[1],reverse = True)
count = 0
i=0
for rest in sortedResturantList:
    Index = rest[0]
    k=df1.iloc[Index]["Restaurant Name"]
    print(k)
    count+=1
    
    if count==10:
        break
    i+=1

Le Petit Souffle
Zen Japanese Steakhouse and Sushi Bar
Kake Di Hatti
Restaurant Mosaic @ The Orient
Sushi Leblon
Restaurant Gordon Ramsay
Tokyo Mon Amour
Baba Au Rhum
La Plage
Les 3 Brasseurs